from heroes.ability import (
    taunt_ability, bastion_ability,    shield_bash_ability,
    smite_ability, holy_shield_ability, healing_light_ability,
    dual_wield_ability, eviscerate_ability, vanish_ability,
    power_shot_ability, spirit_link_ability, quick_step_ability,
    fireball_ability, fire_nova_ability, combustion_ability,
    word_of_healing_ability, circle_of_healing_ability, renew_ability
)
hero_archetypes = [
    {
        'name' : 'Warrior',
        'max_health' : 7,
        'physical_def' : 3,
        'elemental_def' : 5,
        'physical_dmg' : 2,
        'elemental_dmg' : 0,
        'attack_range' : 1,
        'move' : 3,
        'abilities' : [taunt_ability, shield_bash_ability, bastion_ability],
    },
    {
        'name' : 'Paladin',
        'max_health' : 6,
        'physical_def' : 4,
        'elemental_def' : 4,
        'physical_dmg' : 3,
        'elemental_dmg' : 0,
        'attack_range' : 1,
        'move' : 3,
        'abilities' : [smite_ability, holy_shield_ability, healing_light_ability],
    },
    
    {
        'name' : 'Rogue',
        'max_health' : 5,
        'physical_def' : 5,
        'elemental_def' : 5,
        'physical_dmg' : 3,
        'elemental_dmg' : 0,
        'attack_range' : 1,
        'move' : 4,
        'abilities' : [dual_wield_ability, eviscerate_ability, vanish_ability],
    },
    {
        'name' : 'Ranger',
        'max_health' : 5,
        'physical_def' : 5,
        'elemental_def' : 6,
        'physical_dmg' : 3,
        'elemental_dmg' : 0,
        'attack_range' : 4,
        'move' : 4,
        'abilities' : [power_shot_ability, spirit_link_ability, quick_step_ability],
    },
    {
        'name' : 'Mage',
        'max_health' : 5,
        'physical_def' : 7,
        'elemental_def' : 4,
        'physical_dmg' : 0,
        'elemental_dmg' : 2,
        'attack_range' : 4,
        'move' : 3,
        'abilities' : [fireball_ability, fire_nova_ability, combustion_ability],
    },
    {
        'name' : 'Priest',
        'max_health' : 5,
        'physical_def' : 6,
        'elemental_def' : 6,
        'physical_dmg' : 0,
        'elemental_dmg' : 2,
        'attack_range' : 3,
        'move' : 3,
        'abilities' : [word_of_healing_ability, circle_of_healing_ability, renew_ability],
    },
]